import googleIcon from "./assets/googleIcon.png";
import apple from "./assets/apple.png";
import intel from "./assets/intel.png";
export const jobsData = [
  {
    id: 1,
    title: "Technical Support Specialist",
    type: "PART-TIME",
    salary: "20,000 INR - 25,000 INR",
    company: "Google Inc.",
    location: "New Delhi, India",
    applicants: "10+ applicants",
    logo: googleIcon,
    applyLink: "#",
  },
  {
    id: 2,
    title: "Senior UI/UX Designer",
    type: "FULL-TIME",
    salary: "$30,000 - $55,000",
    company: "Apple",
    location: "Boston, USA",
    applicants: "9+ applicants",
    logo: apple,
    applyLink: "#",
  },
  {
    id: 3,
    title: "Marketing Officer",
    type: "PART-TIME",
    salary: "15,000 INR - 35,000 INR",
    company: "Intel Corp",
    location: "Bangalore, India",
    applicants: "30+ applicants",
    logo: intel,
    applyLink: "#",
  },
  {
    id: 4,
    title: "Data Analyst",
    type: "FULL-TIME",
    salary: "$40,000 - $60,000",
    company: "Google Inc.",
    location: "San Francisco, USA",
    applicants: "15+ applicants",
    logo: googleIcon,
    applyLink: "#",
  },
  {
    id: 5,
    title: "Software Engineer",
    type: "FULL-TIME",
    salary: "$80,000 - $120,000",
    company: "Apple",
    location: "Cupertino, USA",
    applicants: "5+ applicants",
    logo: apple,
    applyLink: "#",
  },
  {
    id: 6,
    title: "Graphic Designer",
    type: "PART-TIME",
    salary: "10,000 INR - 20,000 INR",
    company: "Intel Corp",
    location: "Hyderabad, India",
    applicants: "12+ applicants",
    logo: intel,
    applyLink: "#",
  },
  {
    id: 7,
    title: "Product Manager",
    type: "FULL-TIME",
    salary: "$70,000 - $100,000",
    company: "Google Inc.",
    location: "Mountain View, USA",
    applicants: "20+ applicants",
    logo: googleIcon,
    applyLink: "#",
  },
  {
    id: 8,
    title: "HR Specialist",
    type: "PART-TIME",
    salary: "25,000 INR - 35,000 INR",
    company: "Apple",
    location: "Mumbai, India",
    applicants: "18+ applicants",
    logo: apple,
    applyLink: "#",
  },
  {
    id: 9,
    title: "Systems Administrator",
    type: "FULL-TIME",
    salary: "$50,000 - $70,000",
    company: "Intel Corp",
    location: "Delhi, India",
    applicants: "22+ applicants",
    logo: intel,
    applyLink: "#",
  },
  {
    id: 10,
    title: "Content Writer",
    type: "PART-TIME",
    salary: "8,000 INR - 15,000 INR",
    company: "Google Inc.",
    location: "Pune, India",
    applicants: "25+ applicants",
    logo: googleIcon,
    applyLink: "#",
  },
];
